### ISSUE TITLE
Make V8 5.5 ABI compatible with 5.4

### ISSUE THREAD

**Issue by targos** [nodejs/v8#2]
It seems that there are not a lot of things to do to achieve this goal.

I compared the headers of 5.5 and 5.4 with [abi-compliance-checker](https://github.com/lvc/abi-compliance-checker) and the report can be viewed at https://direct.lactame.com/files/nodejs/v8/compat_report.html.

I already fixed the `kJSApiObjectType` and `kJSObjectType` values (see [this commit](https://github.com/targos/node/commit/ffd8cbab2e4bc183da051c4c8b967bc679701dc2)) and now I wonder if anything else is needed.
Also, do we only care about the changes in `v8.h` ?

/cc @nodejs/v8

**Comment by matthewloring** [comment]
The [ABI patch](https://github.com/ofrobots/node/pull/23) for 5.0/5.1 fixed all incompatibilities in the `include` directory (`v8-debug.h`, `v8-platform.h`, etc).

**Comment by rvagg** [comment]
@nodejs/ctc we need to have further discussion about this because of async/await. @ofrobots raised this at the last meeting - V8 doesn't yet have hooks for proper Promise inspection with AsyncHooks et. al. but exposing async/await is going to drive much heavier adoption of native Promises. Is this a situation we are comfortable with in the short term while we wait for deeper hooks or do we want to postpone until we have the tools we need to provide proper runtime inspection?

_FYI if you didn't realise already, 5.5 is the one that unflags async/await, it's really the [only major JS feature](https://www.chromestatus.com/features#shipped_milestone%3D55%20category%3AJavaScript%20impl_status_chrome%3A%22Enabled%20by%20default%22)._

**Comment by bnoordhuis** [comment]
> I already fixed the kJSApiObjectType and kJSObjectType values (see this commit) and now I wonder if anything else is needed.

IndexedPropertyHandlerConfiguration and NamedPropertyHandlerConfiguration picked up extra fields.

EmbedderHeapTracer has new virtual methods.  I would expect that to change the vtable of derived classes but abi-compliance-checker doesn't seem to think it's an issue.

**Comment by targos** [comment]
> EmbedderHeapTracer has new virtual methods

What would be the way to handle it?

Re async/await: We could float a patch to keep it behind a flag until we decide it's ready for production.

**Comment by bnoordhuis** [comment]
You could try reverting it to the old API but in the specific case of EmbedderHeapTracer I'm not sure if it's worth the hassle.  It's only useful to embedders (i.e., node.js, but we don't use it), it's not something add-ons would or should use.  If a tree falls and no one is around to hear it...

**Comment by targos** [comment]
Thanks. I'll move the discussion to a PR where the changes can be more easily seen
